### PR TITLE
Corrected Phaser injection for class extensions

### LINKED ISSUE #80: Injecting your own Phaser does not actually work
🙃 

There are two types of places in code that still rely on a global (`window`) `Phaser` object existing:

* `index.js`, which contains `type: Phaser.AUTO`
* Scene classes that extend from `Phaser.Scene`

Both of the above crash if the global doesn't exist.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #80.

### CODE REVIEW

File: src/scenes/end.js [hunk 1]
```diff
@@ -1,112 +1,114 @@
 import strings from "../assets/strings.js";
 import options from "../options.js";
 
-export default class EndScene extends Phaser.Scene {
```
Comment (JoshuaKGoldberg) [inline src/scenes/end.js:4]: These diffs are a little ugly, but if you view without whitespace, you can see they're mostly indentation.
